#!/usr/bin/env php

<?php
/**
 * Yii console bootstrap file.
 *
 * @link http://www.yiiframework.com/
 * @copyright Copyright (c) 2008 Yii Software LLC
 * @license http://www.yiiframework.com/license/
 */

$ROOT = str_replace('\\', '/', __DIR__) .'/';

require $ROOT .'config/bootstrap.php';

$config = yii\helpers\ArrayHelper::merge([], require $ROOT .'config/console.php');
$application = new yii\console\Application($config);

exit($application->run());
